// source: google/cloud/websecurityscanner/v1alpha/finding.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_cloud_websecurityscanner_v1alpha_finding_addon_pb = require('../../../../google/cloud/websecurityscanner/v1alpha/finding_addon_pb.js');
goog.object.extend(proto, google_cloud_websecurityscanner_v1alpha_finding_addon_pb);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.Finding', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.Finding.FindingType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.websecurityscanner.v1alpha.Finding, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.websecurityscanner.v1alpha.Finding.displayName = 'proto.google.cloud.websecurityscanner.v1alpha.Finding';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.websecurityscanner.v1alpha.Finding.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.Finding} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    findingType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    httpMethod: jspb.Message.getFieldWithDefault(msg, 3, ""),
    fuzzedUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    body: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    reproductionUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    frameUrl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    finalUrl: jspb.Message.getFieldWithDefault(msg, 9, ""),
    trackingId: jspb.Message.getFieldWithDefault(msg, 10, ""),
    outdatedLibrary: (f = msg.getOutdatedLibrary()) && google_cloud_websecurityscanner_v1alpha_finding_addon_pb.OutdatedLibrary.toObject(includeInstance, f),
    violatingResource: (f = msg.getViolatingResource()) && google_cloud_websecurityscanner_v1alpha_finding_addon_pb.ViolatingResource.toObject(includeInstance, f),
    vulnerableParameters: (f = msg.getVulnerableParameters()) && google_cloud_websecurityscanner_v1alpha_finding_addon_pb.VulnerableParameters.toObject(includeInstance, f),
    xss: (f = msg.getXss()) && google_cloud_websecurityscanner_v1alpha_finding_addon_pb.Xss.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.websecurityscanner.v1alpha.Finding;
  return proto.google.cloud.websecurityscanner.v1alpha.Finding.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.Finding} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {!proto.google.cloud.websecurityscanner.v1alpha.Finding.FindingType} */ (reader.readEnum());
      msg.setFindingType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHttpMethod(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFuzzedUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setReproductionUrl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrameUrl(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setFinalUrl(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrackingId(value);
      break;
    case 11:
      var value = new google_cloud_websecurityscanner_v1alpha_finding_addon_pb.OutdatedLibrary;
      reader.readMessage(value,google_cloud_websecurityscanner_v1alpha_finding_addon_pb.OutdatedLibrary.deserializeBinaryFromReader);
      msg.setOutdatedLibrary(value);
      break;
    case 12:
      var value = new google_cloud_websecurityscanner_v1alpha_finding_addon_pb.ViolatingResource;
      reader.readMessage(value,google_cloud_websecurityscanner_v1alpha_finding_addon_pb.ViolatingResource.deserializeBinaryFromReader);
      msg.setViolatingResource(value);
      break;
    case 13:
      var value = new google_cloud_websecurityscanner_v1alpha_finding_addon_pb.VulnerableParameters;
      reader.readMessage(value,google_cloud_websecurityscanner_v1alpha_finding_addon_pb.VulnerableParameters.deserializeBinaryFromReader);
      msg.setVulnerableParameters(value);
      break;
    case 14:
      var value = new google_cloud_websecurityscanner_v1alpha_finding_addon_pb.Xss;
      reader.readMessage(value,google_cloud_websecurityscanner_v1alpha_finding_addon_pb.Xss.deserializeBinaryFromReader);
      msg.setXss(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.websecurityscanner.v1alpha.Finding.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.Finding} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFindingType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getHttpMethod();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFuzzedUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getReproductionUrl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getFrameUrl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getFinalUrl();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getTrackingId();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getOutdatedLibrary();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_cloud_websecurityscanner_v1alpha_finding_addon_pb.OutdatedLibrary.serializeBinaryToWriter
    );
  }
  f = message.getViolatingResource();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_cloud_websecurityscanner_v1alpha_finding_addon_pb.ViolatingResource.serializeBinaryToWriter
    );
  }
  f = message.getVulnerableParameters();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_cloud_websecurityscanner_v1alpha_finding_addon_pb.VulnerableParameters.serializeBinaryToWriter
    );
  }
  f = message.getXss();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_cloud_websecurityscanner_v1alpha_finding_addon_pb.Xss.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.FindingType = {
  FINDING_TYPE_UNSPECIFIED: 0,
  MIXED_CONTENT: 1,
  OUTDATED_LIBRARY: 2,
  ROSETTA_FLASH: 5,
  XSS_CALLBACK: 3,
  XSS_ERROR: 4,
  CLEAR_TEXT_PASSWORD: 6
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional FindingType finding_type = 2;
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding.FindingType}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getFindingType = function() {
  return /** @type {!proto.google.cloud.websecurityscanner.v1alpha.Finding.FindingType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.Finding.FindingType} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setFindingType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string http_method = 3;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getHttpMethod = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setHttpMethod = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string fuzzed_url = 4;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getFuzzedUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setFuzzedUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string body = 5;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string reproduction_url = 7;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getReproductionUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setReproductionUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string frame_url = 8;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getFrameUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setFrameUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string final_url = 9;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getFinalUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setFinalUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string tracking_id = 10;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getTrackingId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setTrackingId = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional OutdatedLibrary outdated_library = 11;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.OutdatedLibrary}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getOutdatedLibrary = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.OutdatedLibrary} */ (
    jspb.Message.getWrapperField(this, google_cloud_websecurityscanner_v1alpha_finding_addon_pb.OutdatedLibrary, 11));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.OutdatedLibrary|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setOutdatedLibrary = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.clearOutdatedLibrary = function() {
  return this.setOutdatedLibrary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.hasOutdatedLibrary = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ViolatingResource violating_resource = 12;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.ViolatingResource}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getViolatingResource = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.ViolatingResource} */ (
    jspb.Message.getWrapperField(this, google_cloud_websecurityscanner_v1alpha_finding_addon_pb.ViolatingResource, 12));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.ViolatingResource|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setViolatingResource = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.clearViolatingResource = function() {
  return this.setViolatingResource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.hasViolatingResource = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional VulnerableParameters vulnerable_parameters = 13;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.VulnerableParameters}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getVulnerableParameters = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.VulnerableParameters} */ (
    jspb.Message.getWrapperField(this, google_cloud_websecurityscanner_v1alpha_finding_addon_pb.VulnerableParameters, 13));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.VulnerableParameters|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setVulnerableParameters = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.clearVulnerableParameters = function() {
  return this.setVulnerableParameters(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.hasVulnerableParameters = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional Xss xss = 14;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.Xss}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.getXss = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.Xss} */ (
    jspb.Message.getWrapperField(this, google_cloud_websecurityscanner_v1alpha_finding_addon_pb.Xss, 14));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.Xss|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.setXss = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.Finding} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.clearXss = function() {
  return this.setXss(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.Finding.prototype.hasXss = function() {
  return jspb.Message.getField(this, 14) != null;
};


goog.object.extend(exports, proto.google.cloud.websecurityscanner.v1alpha);
