// source: google/cloud/websecurityscanner/v1alpha/scan_config.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.AuthenticationCase', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform', null, global);
goog.exportSymbol('proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.UserAgent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.websecurityscanner.v1alpha.ScanConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.displayName = 'proto.google.cloud.websecurityscanner.v1alpha.ScanConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.oneofGroups_);
};
goog.inherits(proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.displayName = 'proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.displayName = 'proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.displayName = 'proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.displayName = 'proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.repeatedFields_ = [4,7,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    displayName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    maxQps: jspb.Message.getFieldWithDefault(msg, 3, 0),
    startingUrlsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    authentication: (f = msg.getAuthentication()) && proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.toObject(includeInstance, f),
    userAgent: jspb.Message.getFieldWithDefault(msg, 6, 0),
    blacklistPatternsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    schedule: (f = msg.getSchedule()) && proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.toObject(includeInstance, f),
    targetPlatformsList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig;
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxQps(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addStartingUrls(value);
      break;
    case 5:
      var value = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication;
      reader.readMessage(value,proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.deserializeBinaryFromReader);
      msg.setAuthentication(value);
      break;
    case 6:
      var value = /** @type {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.UserAgent} */ (reader.readEnum());
      msg.setUserAgent(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addBlacklistPatterns(value);
      break;
    case 8:
      var value = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule;
      reader.readMessage(value,proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.deserializeBinaryFromReader);
      msg.setSchedule(value);
      break;
    case 9:
      var values = /** @type {!Array<!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addTargetPlatforms(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplayName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMaxQps();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getStartingUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getAuthentication();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.serializeBinaryToWriter
    );
  }
  f = message.getUserAgent();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getBlacklistPatternsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getSchedule();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.serializeBinaryToWriter
    );
  }
  f = message.getTargetPlatformsList();
  if (f.length > 0) {
    writer.writePackedEnum(
      9,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.UserAgent = {
  USER_AGENT_UNSPECIFIED: 0,
  CHROME_LINUX: 1,
  CHROME_ANDROID: 2,
  SAFARI_IPHONE: 3
};

/**
 * @enum {number}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform = {
  TARGET_PLATFORM_UNSPECIFIED: 0,
  APP_ENGINE: 1,
  COMPUTE: 2
};


/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.AuthenticationCase = {
  AUTHENTICATION_NOT_SET: 0,
  GOOGLE_ACCOUNT: 1,
  CUSTOM_ACCOUNT: 2
};

/**
 * @return {proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.AuthenticationCase}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.getAuthenticationCase = function() {
  return /** @type {proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.AuthenticationCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.toObject = function(includeInstance, msg) {
  var f, obj = {
    googleAccount: (f = msg.getGoogleAccount()) && proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.toObject(includeInstance, f),
    customAccount: (f = msg.getCustomAccount()) && proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication;
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount;
      reader.readMessage(value,proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.deserializeBinaryFromReader);
      msg.setGoogleAccount(value);
      break;
    case 2:
      var value = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount;
      reader.readMessage(value,proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.deserializeBinaryFromReader);
      msg.setCustomAccount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGoogleAccount();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.serializeBinaryToWriter
    );
  }
  f = message.getCustomAccount();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount;
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, ""),
    loginUrl: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount;
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLoginUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLoginUrl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string login_url = 3;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.getLoginUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount.prototype.setLoginUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional GoogleAccount google_account = 1;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.getGoogleAccount = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount, 1));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.GoogleAccount|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.setGoogleAccount = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.clearGoogleAccount = function() {
  return this.setGoogleAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.hasGoogleAccount = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CustomAccount custom_account = 2;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.getCustomAccount = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount, 2));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.CustomAccount|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.setCustomAccount = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.clearCustomAccount = function() {
  return this.setCustomAccount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication.prototype.hasCustomAccount = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    scheduleTime: (f = msg.getScheduleTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    intervalDurationDays: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule;
  return proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setScheduleTime(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntervalDurationDays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScheduleTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getIntervalDurationDays();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional google.protobuf.Timestamp schedule_time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.getScheduleTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.setScheduleTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.clearScheduleTime = function() {
  return this.setScheduleTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.hasScheduleTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 interval_duration_days = 2;
 * @return {number}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.getIntervalDurationDays = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule.prototype.setIntervalDurationDays = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string display_name = 2;
 * @return {string}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 max_qps = 3;
 * @return {number}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getMaxQps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setMaxQps = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated string starting_urls = 4;
 * @return {!Array<string>}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getStartingUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setStartingUrlsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.addStartingUrls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.clearStartingUrlsList = function() {
  return this.setStartingUrlsList([]);
};


/**
 * optional Authentication authentication = 5;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getAuthentication = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication, 5));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Authentication|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setAuthentication = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.clearAuthentication = function() {
  return this.setAuthentication(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.hasAuthentication = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional UserAgent user_agent = 6;
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.UserAgent}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getUserAgent = function() {
  return /** @type {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.UserAgent} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.UserAgent} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setUserAgent = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * repeated string blacklist_patterns = 7;
 * @return {!Array<string>}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getBlacklistPatternsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setBlacklistPatternsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.addBlacklistPatterns = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.clearBlacklistPatternsList = function() {
  return this.setBlacklistPatternsList([]);
};


/**
 * optional Schedule schedule = 8;
 * @return {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getSchedule = function() {
  return /** @type{?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule, 8));
};


/**
 * @param {?proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.Schedule|undefined} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
*/
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setSchedule = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.clearSchedule = function() {
  return this.setSchedule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.hasSchedule = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated TargetPlatform target_platforms = 9;
 * @return {!Array<!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform>}
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.getTargetPlatformsList = function() {
  return /** @type {!Array<!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform>} value
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.setTargetPlatformsList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.TargetPlatform} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.addTargetPlatforms = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.websecurityscanner.v1alpha.ScanConfig} returns this
 */
proto.google.cloud.websecurityscanner.v1alpha.ScanConfig.prototype.clearTargetPlatformsList = function() {
  return this.setTargetPlatformsList([]);
};


goog.object.extend(exports, proto.google.cloud.websecurityscanner.v1alpha);
