// source: google/cloud/kms/v1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.cloud.kms.v1.CryptoKey', null, global);
goog.exportSymbol('proto.google.cloud.kms.v1.CryptoKey.CryptoKeyPurpose', null, global);
goog.exportSymbol('proto.google.cloud.kms.v1.CryptoKey.RotationScheduleCase', null, global);
goog.exportSymbol('proto.google.cloud.kms.v1.CryptoKeyVersion', null, global);
goog.exportSymbol('proto.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState', null, global);
goog.exportSymbol('proto.google.cloud.kms.v1.KeyRing', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.kms.v1.KeyRing = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.kms.v1.KeyRing, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.kms.v1.KeyRing.displayName = 'proto.google.cloud.kms.v1.KeyRing';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.kms.v1.CryptoKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.google.cloud.kms.v1.CryptoKey.oneofGroups_);
};
goog.inherits(proto.google.cloud.kms.v1.CryptoKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.kms.v1.CryptoKey.displayName = 'proto.google.cloud.kms.v1.CryptoKey';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.kms.v1.CryptoKeyVersion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.kms.v1.CryptoKeyVersion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.kms.v1.CryptoKeyVersion.displayName = 'proto.google.cloud.kms.v1.CryptoKeyVersion';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.kms.v1.KeyRing.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.kms.v1.KeyRing.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.kms.v1.KeyRing} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.kms.v1.KeyRing.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.kms.v1.KeyRing}
 */
proto.google.cloud.kms.v1.KeyRing.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.kms.v1.KeyRing;
  return proto.google.cloud.kms.v1.KeyRing.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.kms.v1.KeyRing} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.kms.v1.KeyRing}
 */
proto.google.cloud.kms.v1.KeyRing.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.kms.v1.KeyRing.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.kms.v1.KeyRing.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.kms.v1.KeyRing} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.kms.v1.KeyRing.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.kms.v1.KeyRing.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.kms.v1.KeyRing} returns this
 */
proto.google.cloud.kms.v1.KeyRing.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.kms.v1.KeyRing.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.kms.v1.KeyRing} returns this
*/
proto.google.cloud.kms.v1.KeyRing.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.KeyRing} returns this
 */
proto.google.cloud.kms.v1.KeyRing.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.KeyRing.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.google.cloud.kms.v1.CryptoKey.oneofGroups_ = [[8]];

/**
 * @enum {number}
 */
proto.google.cloud.kms.v1.CryptoKey.RotationScheduleCase = {
  ROTATION_SCHEDULE_NOT_SET: 0,
  ROTATION_PERIOD: 8
};

/**
 * @return {proto.google.cloud.kms.v1.CryptoKey.RotationScheduleCase}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getRotationScheduleCase = function() {
  return /** @type {proto.google.cloud.kms.v1.CryptoKey.RotationScheduleCase} */(jspb.Message.computeOneofCase(this, proto.google.cloud.kms.v1.CryptoKey.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.kms.v1.CryptoKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.kms.v1.CryptoKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.kms.v1.CryptoKey.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    primary: (f = msg.getPrimary()) && proto.google.cloud.kms.v1.CryptoKeyVersion.toObject(includeInstance, f),
    purpose: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    nextRotationTime: (f = msg.getNextRotationTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    rotationPeriod: (f = msg.getRotationPeriod()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    labelsMap: (f = msg.getLabelsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.kms.v1.CryptoKey}
 */
proto.google.cloud.kms.v1.CryptoKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.kms.v1.CryptoKey;
  return proto.google.cloud.kms.v1.CryptoKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.kms.v1.CryptoKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.kms.v1.CryptoKey}
 */
proto.google.cloud.kms.v1.CryptoKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = new proto.google.cloud.kms.v1.CryptoKeyVersion;
      reader.readMessage(value,proto.google.cloud.kms.v1.CryptoKeyVersion.deserializeBinaryFromReader);
      msg.setPrimary(value);
      break;
    case 3:
      var value = /** @type {!proto.google.cloud.kms.v1.CryptoKey.CryptoKeyPurpose} */ (reader.readEnum());
      msg.setPurpose(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setNextRotationTime(value);
      break;
    case 8:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRotationPeriod(value);
      break;
    case 10:
      var value = msg.getLabelsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.kms.v1.CryptoKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.kms.v1.CryptoKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.kms.v1.CryptoKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPrimary();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.cloud.kms.v1.CryptoKeyVersion.serializeBinaryToWriter
    );
  }
  f = message.getPurpose();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getNextRotationTime();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getRotationPeriod();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getLabelsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.kms.v1.CryptoKey.CryptoKeyPurpose = {
  CRYPTO_KEY_PURPOSE_UNSPECIFIED: 0,
  ENCRYPT_DECRYPT: 1
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CryptoKeyVersion primary = 2;
 * @return {?proto.google.cloud.kms.v1.CryptoKeyVersion}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getPrimary = function() {
  return /** @type{?proto.google.cloud.kms.v1.CryptoKeyVersion} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.kms.v1.CryptoKeyVersion, 2));
};


/**
 * @param {?proto.google.cloud.kms.v1.CryptoKeyVersion|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
*/
proto.google.cloud.kms.v1.CryptoKey.prototype.setPrimary = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.clearPrimary = function() {
  return this.setPrimary(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.hasPrimary = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CryptoKeyPurpose purpose = 3;
 * @return {!proto.google.cloud.kms.v1.CryptoKey.CryptoKeyPurpose}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getPurpose = function() {
  return /** @type {!proto.google.cloud.kms.v1.CryptoKey.CryptoKeyPurpose} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.google.cloud.kms.v1.CryptoKey.CryptoKeyPurpose} value
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.setPurpose = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
*/
proto.google.cloud.kms.v1.CryptoKey.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp next_rotation_time = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getNextRotationTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
*/
proto.google.cloud.kms.v1.CryptoKey.prototype.setNextRotationTime = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.clearNextRotationTime = function() {
  return this.setNextRotationTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.hasNextRotationTime = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Duration rotation_period = 8;
 * @return {?proto.google.protobuf.Duration}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getRotationPeriod = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 8));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
*/
proto.google.cloud.kms.v1.CryptoKey.prototype.setRotationPeriod = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.google.cloud.kms.v1.CryptoKey.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.clearRotationPeriod = function() {
  return this.setRotationPeriod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.hasRotationPeriod = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * map<string, string> labels = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.getLabelsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.google.cloud.kms.v1.CryptoKey} returns this
 */
proto.google.cloud.kms.v1.CryptoKey.prototype.clearLabelsMap = function() {
  this.getLabelsMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.kms.v1.CryptoKeyVersion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.kms.v1.CryptoKeyVersion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    state: jspb.Message.getFieldWithDefault(msg, 3, 0),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    destroyTime: (f = msg.getDestroyTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    destroyEventTime: (f = msg.getDestroyEventTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.kms.v1.CryptoKeyVersion;
  return proto.google.cloud.kms.v1.CryptoKeyVersion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.kms.v1.CryptoKeyVersion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {!proto.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDestroyTime(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDestroyEventTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.kms.v1.CryptoKeyVersion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.kms.v1.CryptoKeyVersion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDestroyTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDestroyEventTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState = {
  CRYPTO_KEY_VERSION_STATE_UNSPECIFIED: 0,
  ENABLED: 1,
  DISABLED: 2,
  DESTROYED: 3,
  DESTROY_SCHEDULED: 4
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CryptoKeyVersionState state = 3;
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.getState = function() {
  return /** @type {!proto.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.google.cloud.kms.v1.CryptoKeyVersion.CryptoKeyVersionState} value
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
*/
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp destroy_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.getDestroyTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
*/
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.setDestroyTime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.clearDestroyTime = function() {
  return this.setDestroyTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.hasDestroyTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp destroy_event_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.getDestroyEventTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
*/
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.setDestroyEventTime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.kms.v1.CryptoKeyVersion} returns this
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.clearDestroyEventTime = function() {
  return this.setDestroyEventTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.kms.v1.CryptoKeyVersion.prototype.hasDestroyEventTime = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.google.cloud.kms.v1);
