// source: google/cloud/asset/v1beta1/assets.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_iam_v1_policy_pb = require('../../../../google/iam/v1/policy_pb.js');
goog.object.extend(proto, google_iam_v1_policy_pb);
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.cloud.asset.v1beta1.Asset', null, global);
goog.exportSymbol('proto.google.cloud.asset.v1beta1.Resource', null, global);
goog.exportSymbol('proto.google.cloud.asset.v1beta1.TemporalAsset', null, global);
goog.exportSymbol('proto.google.cloud.asset.v1beta1.TimeWindow', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.asset.v1beta1.TemporalAsset = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.asset.v1beta1.TemporalAsset, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.asset.v1beta1.TemporalAsset.displayName = 'proto.google.cloud.asset.v1beta1.TemporalAsset';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.asset.v1beta1.TimeWindow = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.asset.v1beta1.TimeWindow, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.asset.v1beta1.TimeWindow.displayName = 'proto.google.cloud.asset.v1beta1.TimeWindow';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.asset.v1beta1.Asset = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.asset.v1beta1.Asset, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.asset.v1beta1.Asset.displayName = 'proto.google.cloud.asset.v1beta1.Asset';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.asset.v1beta1.Resource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.asset.v1beta1.Resource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.asset.v1beta1.Resource.displayName = 'proto.google.cloud.asset.v1beta1.Resource';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.asset.v1beta1.TemporalAsset.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.asset.v1beta1.TemporalAsset} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.toObject = function(includeInstance, msg) {
  var f, obj = {
    window: (f = msg.getWindow()) && proto.google.cloud.asset.v1beta1.TimeWindow.toObject(includeInstance, f),
    deleted: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    asset: (f = msg.getAsset()) && proto.google.cloud.asset.v1beta1.Asset.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.asset.v1beta1.TemporalAsset;
  return proto.google.cloud.asset.v1beta1.TemporalAsset.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.asset.v1beta1.TemporalAsset} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.asset.v1beta1.TimeWindow;
      reader.readMessage(value,proto.google.cloud.asset.v1beta1.TimeWindow.deserializeBinaryFromReader);
      msg.setWindow(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDeleted(value);
      break;
    case 3:
      var value = new proto.google.cloud.asset.v1beta1.Asset;
      reader.readMessage(value,proto.google.cloud.asset.v1beta1.Asset.deserializeBinaryFromReader);
      msg.setAsset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.asset.v1beta1.TemporalAsset.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.asset.v1beta1.TemporalAsset} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWindow();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.asset.v1beta1.TimeWindow.serializeBinaryToWriter
    );
  }
  f = message.getDeleted();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAsset();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.cloud.asset.v1beta1.Asset.serializeBinaryToWriter
    );
  }
};


/**
 * optional TimeWindow window = 1;
 * @return {?proto.google.cloud.asset.v1beta1.TimeWindow}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.getWindow = function() {
  return /** @type{?proto.google.cloud.asset.v1beta1.TimeWindow} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.asset.v1beta1.TimeWindow, 1));
};


/**
 * @param {?proto.google.cloud.asset.v1beta1.TimeWindow|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset} returns this
*/
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.setWindow = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset} returns this
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.clearWindow = function() {
  return this.setWindow(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.hasWindow = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool deleted = 2;
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.getDeleted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset} returns this
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.setDeleted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional Asset asset = 3;
 * @return {?proto.google.cloud.asset.v1beta1.Asset}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.getAsset = function() {
  return /** @type{?proto.google.cloud.asset.v1beta1.Asset} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.asset.v1beta1.Asset, 3));
};


/**
 * @param {?proto.google.cloud.asset.v1beta1.Asset|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset} returns this
*/
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.setAsset = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.TemporalAsset} returns this
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.clearAsset = function() {
  return this.setAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.TemporalAsset.prototype.hasAsset = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.asset.v1beta1.TimeWindow.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.asset.v1beta1.TimeWindow} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.TimeWindow.toObject = function(includeInstance, msg) {
  var f, obj = {
    startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endTime: (f = msg.getEndTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.asset.v1beta1.TimeWindow}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.asset.v1beta1.TimeWindow;
  return proto.google.cloud.asset.v1beta1.TimeWindow.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.asset.v1beta1.TimeWindow} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.asset.v1beta1.TimeWindow}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.asset.v1beta1.TimeWindow.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.asset.v1beta1.TimeWindow} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.TimeWindow.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp start_time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.TimeWindow} returns this
*/
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.TimeWindow} returns this
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.TimeWindow} returns this
*/
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.TimeWindow} returns this
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.TimeWindow.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.asset.v1beta1.Asset.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.asset.v1beta1.Asset} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.Asset.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    assetType: jspb.Message.getFieldWithDefault(msg, 2, ""),
    resource: (f = msg.getResource()) && proto.google.cloud.asset.v1beta1.Resource.toObject(includeInstance, f),
    iamPolicy: (f = msg.getIamPolicy()) && google_iam_v1_policy_pb.Policy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.asset.v1beta1.Asset}
 */
proto.google.cloud.asset.v1beta1.Asset.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.asset.v1beta1.Asset;
  return proto.google.cloud.asset.v1beta1.Asset.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.asset.v1beta1.Asset} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.asset.v1beta1.Asset}
 */
proto.google.cloud.asset.v1beta1.Asset.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssetType(value);
      break;
    case 3:
      var value = new proto.google.cloud.asset.v1beta1.Resource;
      reader.readMessage(value,proto.google.cloud.asset.v1beta1.Resource.deserializeBinaryFromReader);
      msg.setResource(value);
      break;
    case 4:
      var value = new google_iam_v1_policy_pb.Policy;
      reader.readMessage(value,google_iam_v1_policy_pb.Policy.deserializeBinaryFromReader);
      msg.setIamPolicy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.asset.v1beta1.Asset.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.asset.v1beta1.Asset} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.Asset.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAssetType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getResource();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.cloud.asset.v1beta1.Resource.serializeBinaryToWriter
    );
  }
  f = message.getIamPolicy();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_iam_v1_policy_pb.Policy.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Asset} returns this
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string asset_type = 2;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.getAssetType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Asset} returns this
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.setAssetType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Resource resource = 3;
 * @return {?proto.google.cloud.asset.v1beta1.Resource}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.getResource = function() {
  return /** @type{?proto.google.cloud.asset.v1beta1.Resource} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.asset.v1beta1.Resource, 3));
};


/**
 * @param {?proto.google.cloud.asset.v1beta1.Resource|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.Asset} returns this
*/
proto.google.cloud.asset.v1beta1.Asset.prototype.setResource = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.Asset} returns this
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.clearResource = function() {
  return this.setResource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.hasResource = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.iam.v1.Policy iam_policy = 4;
 * @return {?proto.google.iam.v1.Policy}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.getIamPolicy = function() {
  return /** @type{?proto.google.iam.v1.Policy} */ (
    jspb.Message.getWrapperField(this, google_iam_v1_policy_pb.Policy, 4));
};


/**
 * @param {?proto.google.iam.v1.Policy|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.Asset} returns this
*/
proto.google.cloud.asset.v1beta1.Asset.prototype.setIamPolicy = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.Asset} returns this
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.clearIamPolicy = function() {
  return this.setIamPolicy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.Asset.prototype.hasIamPolicy = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.asset.v1beta1.Resource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.asset.v1beta1.Resource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.Resource.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, ""),
    discoveryDocumentUri: jspb.Message.getFieldWithDefault(msg, 2, ""),
    discoveryName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    resourceUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    parent: jspb.Message.getFieldWithDefault(msg, 5, ""),
    data: (f = msg.getData()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.asset.v1beta1.Resource}
 */
proto.google.cloud.asset.v1beta1.Resource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.asset.v1beta1.Resource;
  return proto.google.cloud.asset.v1beta1.Resource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.asset.v1beta1.Resource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.asset.v1beta1.Resource}
 */
proto.google.cloud.asset.v1beta1.Resource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscoveryDocumentUri(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiscoveryName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 6:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.asset.v1beta1.Resource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.asset.v1beta1.Resource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.asset.v1beta1.Resource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDiscoveryDocumentUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDiscoveryName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getResourceUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};


/**
 * optional string version = 1;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string discovery_document_uri = 2;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.getDiscoveryDocumentUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.setDiscoveryDocumentUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string discovery_name = 3;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.getDiscoveryName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.setDiscoveryName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string resource_url = 4;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.getResourceUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.setResourceUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string parent = 5;
 * @return {string}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.setParent = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional google.protobuf.Struct data = 6;
 * @return {?proto.google.protobuf.Struct}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.getData = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 6));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
*/
proto.google.cloud.asset.v1beta1.Resource.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.asset.v1beta1.Resource} returns this
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.asset.v1beta1.Resource.prototype.hasData = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.google.cloud.asset.v1beta1);
